apiVersion: v1
kind: Service
metadata:
  name: test-k8s-service
spec:
  selector:
    app: test-k8s-deployment
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
